In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import joypy
from pandas.plotting import table 
from scipy.stats import linregress
from scipy.stats import describe
from sklearn import datasets
import statsmodels.api as sm
from sklearn.metrics import precision_score, accuracy_score
sns.set_theme(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

In [3]:
file = "/Users/mdcummings/Desktop/Data Analysis/Boot Camp/Project 4/Project 4/Project 4/project-4-repository/Resources/Combined_Flights_2022.csv"

In [4]:
df = pd.read_csv(file)


In [5]:
list(df.head(10))

['FlightDate',
 'Airline',
 'Origin',
 'Dest',
 'Cancelled',
 'Diverted',
 'CRSDepTime',
 'DepTime',
 'DepDelayMinutes',
 'DepDelay',
 'ArrTime',
 'ArrDelayMinutes',
 'AirTime',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'Distance',
 'Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'Marketing_Airline_Network',
 'Operated_or_Branded_Code_Share_Partners',
 'DOT_ID_Marketing_Airline',
 'IATA_Code_Marketing_Airline',
 'Flight_Number_Marketing_Airline',
 'Operating_Airline',
 'DOT_ID_Operating_Airline',
 'IATA_Code_Operating_Airline',
 'Tail_Number',
 'Flight_Number_Operating_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRS

In [6]:
#sort values by flight 
sorted_df = df.sort_values('FlightDate')
sorted_df.head(5)

FlightDate                 Airline Origin Dest  Cancelled  Diverted  \
3352803  2022-01-01   SkyWest Airlines Inc.    DEN  LAX      False     False   
3084349  2022-01-01  Southwest Airlines Co.    BDL  BNA      False     False   
3084350  2022-01-01  Southwest Airlines Co.    BDL  BWI      False     False   
3084351  2022-01-01  Southwest Airlines Co.    BDL  BWI      False     False   
3084352  2022-01-01  Southwest Airlines Co.    BDL  BWI       True     False   

         CRSDepTime  DepTime  DepDelayMinutes  DepDelay  ...  WheelsOff  \
3352803         600    852.0            172.0     172.0  ...      942.0   
3084349        1430   1428.0              0.0      -2.0  ...     1438.0   
3084350        1235   1313.0             38.0      38.0  ...     1324.0   
3084351         525    531.0              6.0       6.0  ...      541.0   
3084352        1710      NaN              NaN       NaN  ...        NaN   

         WheelsOn  TaxiIn  CRSArrTime  ArrDelay  ArrDel15  ArrivalDelayGroups  \
3352803    1042.0     7.0         756     173.0       1.0                11.0   
3084349    1608.0    10.0        1610       8.0       0.0                 0.0   
3084350    1421.0     5.0        1350      36.0       1.0                 2.0   
3084351     633.0    20.0         645       8.0       0.0                 0.0   
3084352       NaN     NaN        1830       NaN       NaN                 NaN   

         ArrTimeBlk  DistanceGroup  DivAirportLandings  
3352803   0700-0759              4                   0  
3084349   1600-1659              4                   0  
3084350   1300-1359              2                   0  
3084351   0600-0659              2                   0  
3084352   1800-1859              2                   0  

[5 rows x 61 columns]

In [7]:
# Understand the data types in each column
df.dtypes

FlightDate             object
Airline                object
Origin                 object
Dest                   object
Cancelled                bool
                       ...   
ArrDel15              float64
ArrivalDelayGroups    float64
ArrTimeBlk             object
DistanceGroup           int64
DivAirportLandings      int64
Length: 61, dtype: object

In [8]:
# Describe the data
df.describe()


CRSDepTime       DepTime  DepDelayMinutes      DepDelay  \
count  4.078318e+06  3.957885e+06     3.957823e+06  3.957823e+06   
mean   1.329587e+03  1.334374e+03     1.601494e+01  1.309049e+01   
std    4.904801e+02  5.056219e+02     5.231498e+01  5.332016e+01   
min    1.000000e+00  1.000000e+00     0.000000e+00 -7.800000e+01   
25%    9.140000e+02  9.170000e+02     0.000000e+00 -5.000000e+00   
50%    1.320000e+03  1.325000e+03     0.000000e+00 -2.000000e+00   
75%    1.735000e+03  1.744000e+03     1.100000e+01  1.100000e+01   
max    2.359000e+03  2.400000e+03     7.223000e+03  7.223000e+03   

            ArrTime  ArrDelayMinutes       AirTime  CRSElapsedTime  \
count  3.954079e+06     3.944916e+06  3.944916e+06    4.078318e+06   
mean   1.457886e+03     1.578307e+01  1.110075e+02    1.413211e+02   
std    5.431841e+02     5.198424e+01  6.996246e+01    7.179635e+01   
min    1.000000e+00     0.000000e+00  8.000000e+00   -4.800000e+01   
25%    1.046000e+03     0.000000e+00  6.000000e+01    8.900000e+01   
50%    1.500000e+03     0.000000e+00  9.400000e+01    1.240000e+02   
75%    1.914000e+03     1.000000e+01  1.410000e+02    1.710000e+02   
max    2.400000e+03     7.232000e+03  7.270000e+02    6.900000e+02   

       ActualElapsedTime      Distance  ...       TaxiOut     WheelsOff  \
count       3.944916e+06  4.078318e+06  ...  3.955652e+06  3.955652e+06   
mean        1.358624e+02  7.978657e+02  ...  1.697375e+01  1.356576e+03   
std         7.185501e+01  5.914742e+02  ...  9.495407e+00  5.075580e+02   
min         1.400000e+01  3.100000e+01  ...  1.000000e+00  1.000000e+00   
25%         8.300000e+01  3.680000e+02  ...  1.100000e+01  9.320000e+02   
50%         1.190000e+02  6.430000e+02  ...  1.500000e+01  1.338000e+03   
75%         1.670000e+02  1.035000e+03  ...  1.900000e+01  1.758000e+03   
max         7.640000e+02  5.095000e+03  ...  2.210000e+02  2.400000e+03   

           WheelsOn        TaxiIn    CRSArrTime      ArrDelay      ArrDel15  \
count  3.954076e+06  3.954076e+06  4.078318e+06  3.944916e+06  3.944916e+06   
mean   1.455073e+03  7.894387e+00  1.486058e+03  7.528486e+00  2.164715e-01   
std    5.378428e+02  6.663118e+00  5.185078e+02  5.524625e+01  4.118393e-01   
min    1.000000e+00  1.000000e+00  1.000000e+00 -1.000000e+02  0.000000e+00   
25%    1.044000e+03  4.000000e+00  1.103000e+03 -1.400000e+01  0.000000e+00   
50%    1.456000e+03  6.000000e+00  1.513000e+03 -5.000000e+00  0.000000e+00   
75%    1.909000e+03  9.000000e+00  1.920000e+03  1.000000e+01  0.000000e+00   
max    2.400000e+03  2.900000e+02  2.359000e+03  7.232000e+03  1.000000e+00   

       ArrivalDelayGroups  DistanceGroup  DivAirportLandings  
count        3.944916e+06   4.078318e+06        4.078318e+06  
mean        -6.256103e-02   3.663516e+00        3.685098e-03  
std          2.487442e+00   2.320848e+00        1.141331e-01  
min         -2.000000e+00   1.000000e+00        0.000000e+00  
25%         -1.000000e+00   2.000000e+00        0.000000e+00  
50%         -1.000000e+00   3.000000e+00        0.000000e+00  
75%          0.000000e+00   5.000000e+00        0.000000e+00  
max          1.200000e+01   1.100000e+01        9.000000e+00  

[8 rows x 41 columns]

In [9]:
# Only proceed with the following columns
essential_column_list = [
    'Flight_Number_Operating_Airline',	
    'Month',
    'DayofMonth',
    'DayOfWeek',
    'OriginAirportID',
    'CRSDepTime',
    'DepTime', 
    'DestAirportID',
    'CRSArrTime',
    'ArrTime',
    'ArrDelayMinutes',
    'DepDelayMinutes',
    'Cancelled',
    ]
essential_df = df[essential_column_list]
essential_df.head(10)

Flight_Number_Operating_Airline  Month  DayofMonth  DayOfWeek  \
0                             4301      4           4          1   
1                             4299      4           4          1   
2                             4298      4           4          1   
3                             4296      4           4          1   
4                             4295      4           4          1   
5                             4294      4           4          1   
6                             4293      4           4          1   
7                             4292      4           4          1   
8                             4291      4           4          1   
9                             4290      4           4          1   

   OriginAirportID  CRSDepTime  DepTime  DestAirportID  CRSArrTime  ArrTime  \
0            11921        1133   1123.0          11292        1245   1228.0   
1            12206         732    728.0          12266         849    848.0   
2            11413        1529   1514.0          11292        1639   1636.0   
3            12266        1435   1430.0          11973        1605   1547.0   
4            11413        1135   1135.0          11292        1245   1251.0   
5            11292         955    952.0          15370        1240   1238.0   
6            12266        2139   2136.0          12915        2231   2218.0   
7            15412        1129   1117.0          12266        1306   1311.0   
8            12266        1424   1414.0          10185        1524   1513.0   
9            12266         954    947.0          13422        1121   1110.0   

   ArrDelayMinutes  DepDelayMinutes  Cancelled  
0              0.0              0.0      False  
1              0.0              0.0      False  
2              0.0              0.0      False  
3              0.0              0.0      False  
4              6.0              0.0      False  
5              0.0              0.0      False  
6              0.0              0.0      False  
7              5.0              0.0      False  
8              0.0              0.0      False  
9              0.0              0.0      False

In [10]:
# creating a column showing "2" for cancelled, "1" for delayed, and "0" for on time flights
cancelled_condition = essential_df['Cancelled'] == True
delayed_condition = essential_df['DepDelayMinutes'] > 1
ontime_condition = essential_df['DepDelayMinutes'] == 0

status = ["2", "1", "0"]

# Using .loc to assign values to the 'Status' column
essential_df.loc[cancelled_condition, 'Status'] = status[0]
essential_df.loc[delayed_condition, 'Status'] = status[1]
essential_df.loc[ontime_condition, 'Status'] = status[2]
    
essential_df.head()

/var/folders/nr/jqfs4n8n3bvf1cmmq9_jmc5c0000gn/T/ipykernel_41329/2197377963.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  essential_df.loc[cancelled_condition, 'Status'] = status[0]


Flight_Number_Operating_Airline  Month  DayofMonth  DayOfWeek  \
0                             4301      4           4          1   
1                             4299      4           4          1   
2                             4298      4           4          1   
3                             4296      4           4          1   
4                             4295      4           4          1   

   OriginAirportID  CRSDepTime  DepTime  DestAirportID  CRSArrTime  ArrTime  \
0            11921        1133   1123.0          11292        1245   1228.0   
1            12206         732    728.0          12266         849    848.0   
2            11413        1529   1514.0          11292        1639   1636.0   
3            12266        1435   1430.0          11973        1605   1547.0   
4            11413        1135   1135.0          11292        1245   1251.0   

   ArrDelayMinutes  DepDelayMinutes  Cancelled Status  
0              0.0              0.0      False      0  
1              0.0              0.0      False      0  
2              0.0              0.0      False      0  
3              0.0              0.0      False      0  
4              6.0              0.0      False      0

In [11]:
# remove the Cancelled column
df_clean = essential_df.drop(columns=['Cancelled'], axis=1)

In [12]:
# Convert new Status column to float and display the datatypes for each column
df_clean['Status'] = df_clean['Status'].astype(float)
print(df_clean.dtypes)

Flight_Number_Operating_Airline      int64
Month                                int64
DayofMonth                           int64
DayOfWeek                            int64
OriginAirportID                      int64
CRSDepTime                           int64
DepTime                            float64
DestAirportID                        int64
CRSArrTime                           int64
ArrTime                            float64
ArrDelayMinutes                    float64
DepDelayMinutes                    float64
Status                             float64
dtype: object


In [13]:
# Look at the value counts for binning
flight_no_airline_count = df_clean['Flight_Number_Operating_Airline'].value_counts()
flight_no_airline_count

772     1842
418     1828
770     1806
573     1791
61      1687
        ... 
6692       1
6958       1
6407       1
6672       1
6490       1
Name: Flight_Number_Operating_Airline, Length: 6793, dtype: int64

In [20]:
# You may find it helpful to look at Flight Numbers value counts > 750
flight_no_over_1 = flight_no_airline_count[flight_no_airline_count> 750]
flight_no_over_1.head(50)

772     1842
418     1828
770     1806
573     1791
61      1687
679     1644
2142    1642
698     1634
2127    1627
340     1621
841     1620
62      1610
1095    1597
2051    1596
676     1589
2147    1587
712     1585
683     1577
1244    1574
1430    1573
538     1571
2338    1567
2095    1566
371     1561
535     1558
565     1558
517     1554
2120    1549
2122    1549
2135    1546
639     1543
2078    1542
327     1535
2339    1533
2424    1528
366     1525
358     1525
1254    1520
352     1516
778     1508
334     1507
1623    1506
1101    1506
1678    1505
688     1502
686     1495
372     1494
1199    1493
2087    1492
1418    1491
Name: Flight_Number_Operating_Airline, dtype: int64

In [21]:
# Choose a cutoff value and create a list of classifications to be replaced
# using the variable name `flight_no_to_replace`for value counts over 600 
flight_no_to_replace = list(flight_no_over_1[flight_no_over_1 < 600].index)

# Replace in dataframe
for cls in flight_no_to_replace:
    df_clean['Flight_Number_Operating_Airline'] = df_clean['Flight_Number_Operating_Airline'].replace(cls,"0")

# Check to make sure binning was successful
df_clean['Flight_Number_Operating_Airline'].value_counts()

0       2641392
772        1842
418        1828
770        1806
573        1791
         ...   
6681          1
6759          1
6676          1
6682          1
6490          1
Name: Flight_Number_Operating_Airline, Length: 3934, dtype: int64

In [22]:
# Handle non-finite values by replacing them with a placeholder (e.g., 0)
df_clean.replace([np.inf, -np.inf, np.nan], 0, inplace=True)

In [23]:
# Check the data types
df_clean.dtypes

Flight_Number_Operating_Airline     object
Month                                int64
DayofMonth                           int64
DayOfWeek                            int64
OriginAirportID                      int64
CRSDepTime                           int64
DepTime                            float64
DestAirportID                        int64
CRSArrTime                           int64
ArrTime                            float64
ArrDelayMinutes                    float64
DepDelayMinutes                    float64
Status                             float64
dtype: object

In [25]:
# Convert categorical data to numeric with OneHotEncoder 
# Import the encoder
# from sklearn.preprocessing import OneHotEncoder
# # Create the encoder.
# encoder = OneHotEncoder()
# encoder.fit_transform(df_clean) 
 

In [26]:
df_clean.head(5)

Flight_Number_Operating_Airline  Month  DayofMonth  DayOfWeek  \
0                            4301      4           4          1   
1                            4299      4           4          1   
2                            4298      4           4          1   
3                            4296      4           4          1   
4                            4295      4           4          1   

   OriginAirportID  CRSDepTime  DepTime  DestAirportID  CRSArrTime  ArrTime  \
0            11921        1133   1123.0          11292        1245   1228.0   
1            12206         732    728.0          12266         849    848.0   
2            11413        1529   1514.0          11292        1639   1636.0   
3            12266        1435   1430.0          11973        1605   1547.0   
4            11413        1135   1135.0          11292        1245   1251.0   

   ArrDelayMinutes  DepDelayMinutes  Status  
0              0.0              0.0     0.0  
1              0.0              0.0     0.0  
2              0.0              0.0     0.0  
3              0.0              0.0     0.0  
4              6.0              0.0     0.0

In [27]:
# Split our data into training and testing and establish features and target variable
from sklearn.model_selection import train_test_split
features = df_clean.drop('Status', axis=1)
targets = df_clean['Status']

X_train, X_test, y_train, y_test = train_test_split(features,
                                                    targets,
                                                    random_state=42,
                                                    stratify=targets)

In [28]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [29]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X_train)

In [30]:
# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [31]:
# Utilize CatBoost Classifier to initialize, train and make predictions
# initialize data
from catboost import CatBoostClassifier, Pool
train_data = df_clean.drop(columns=['Status'])

train_labels = df_clean['Status']

test_data = catboost_pool = Pool(train_data, 
                                 train_labels)

model = CatBoostClassifier(iterations=4,
                           depth=2,
                           learning_rate=1,
                           loss_function='MultiClass',
                           verbose=True)
# train the model
model.fit(train_data, train_labels)
# make the prediction using the resulting model
preds_class = model.predict(test_data)
preds_proba = model.predict_proba(test_data)
print("class = ", preds_class)
print("proba = ", preds_proba)

0:	learn: 0.0954874	total: 43.2s	remaining: 2m 9s
1:	learn: 0.0330165	total: 47.4s	remaining: 47.4s
2:	learn: 0.0119587	total: 47.6s	remaining: 15.9s
3:	learn: 0.0044349	total: 47.9s	remaining: 0us
class =  [[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [0.]]
proba =  [[0.99578963 0.00213125 0.00207912]
 [0.99578963 0.00213125 0.00207912]
 [0.99578963 0.00213125 0.00207912]
 ...
 [0.00213642 0.99572715 0.00213642]
 [0.00213642 0.99572715 0.00213642]
 [0.99578963 0.00213125 0.00207912]]


In [33]:
# fit the data
catboost_train_data = Pool(X_train,y_train)

cb_model = CatBoostClassifier()



In [34]:
cb_model.fit(catboost_train_data, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.119148
0:	learn: 0.8750549	total: 2m 15s	remaining: 1d 13h 36m 4s
1:	learn: 0.7184496	total: 3m 12s	remaining: 1d 2h 43m 15s
2:	learn: 0.6007183	total: 3m 13s	remaining: 17h 49m 7s
3:	learn: 0.5084505	total: 3m 13s	remaining: 13h 22m 13s
4:	learn: 0.4341404	total: 3m 13s	remaining: 10h 41m 54s
5:	learn: 0.3731684	total: 3m 13s	remaining: 8h 55m
6:	learn: 0.3224288	total: 3m 13s	remaining: 7h 38m 38s
7:	learn: 0.2797458	total: 3m 14s	remaining: 6h 41m 24s
8:	learn: 0.2435289	total: 3m 14s	remaining: 5h 56m 56s
9:	learn: 0.2126063	total: 3m 14s	remaining: 5h 21m 19s
10:	learn: 0.1860389	total: 3m 14s	remaining: 4h 52m 6s
11:	learn: 0.1631148	total: 3m 15s	remaining: 4h 27m 49s
12:	learn: 0.1432381	total: 3m 15s	remaining: 4h 7m 15s
13:	learn: 0.1259616	total: 3m 15s	remaining: 3h 49m 39s
14:	learn: 0.1109029	total: 3m 15s	remaining: 3h 34m 22s
15:	learn: 0.0977576	total: 3m 16s	remaining: 3h 21m
16:	learn: 0.0862396	total: 3m 16s	remaining: 3h 9m 15s
17:	learn: 0.0

In [35]:
# Use the fitted model to make predictions
cb_model.predict(catboost_train_data)


array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [36]:
# Get the best score
cb_model.get_best_score()

{'learn': {'MultiClass': 8.481906415713473e-06}}

In [37]:
# Score
cb_model.score(df_clean, df_clean['Status'])

0.9999948508184011

In [38]:
#Make predictions on the test set
y_pred = cb_model.predict(X_test)
y_pred

array([[1.],
       [0.],
       [1.],
       ...,
       [1.],
       [0.],
       [1.]])

In [45]:
# Calculate precision score
precision = precision_score(y_test, y_pred, average='weighted')
precision

0.9999794022439765

In [46]:
# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.999979403283705

In [47]:
# Evaluate the model using the test data
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.svm import SVC

# Calculating the confusion matrix
target_names=["On-Time", "Delayed", "Cancelled"]

cm = multilabel_confusion_matrix(y_test, y_pred)
# cm_df = pd.DataFrame(
#     cm, index=target_names, columns=target_names
# )
cm





array([[[397652,     18],
        [     3, 621907]],

       [[652041,      0],
        [     0, 367539]],

       [[989446,      3],
        [    18,  30113]]])

In [48]:
# Print the classification report for the model
target_names=["On-Time", "Delayed", "Cancelled"]
print("Confusion Matrix:")
print(cm) 
print("Accuracy Score:", accuracy) 
print("Classification Report")
print(classification_report(y_test, y_pred, labels=[0,1,2]))

Confusion Matrix:
[[[397652     18]
  [     3 621907]]

 [[652041      0]
  [     0 367539]]

 [[989446      3]
  [    18  30113]]]
Accuracy Score: 0.999979403283705
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    621910
           1       1.00      1.00      1.00    367539
           2       1.00      1.00      1.00     30131

    accuracy                           1.00   1019580
   macro avg       1.00      1.00      1.00   1019580
weighted avg       1.00      1.00      1.00   1019580



In [ ]:
# Calculate and plot a set of statistics for the chosen feature.

plot = cb_model.calc_feature_statistics(df_clean,
                        target=train_labels,
                        feature=train_data,
                        prediction_type='Class',
                        cat_feature_values=None,
                        plot=True,
                        max_cat_features_on_plot=10,
                        thread_count=-1,
                        plot_file=None)